// Human-readable names for Binance base assets. Symbols missing here
// fall back to the symbol itself.
export const COIN_NAMES: Record<string, string> = {
  BTC: "Bitcoin",
  ETH: "Ethereum",
  USDT: "Tether",
  BNB: "BNB",
  SOL: "Solana",
  XRP: "XRP",
  USDC: "USD Coin",
  ADA: "Cardano",
  DOGE: "Dogecoin",
  TRX: "TRON",
  TON: "Toncoin",
  AVAX: "Avalanche",
  SHIB: "Shiba Inu",
  DOT: "Polkadot",
  LINK: "Chainlink",
  BCH: "Bitcoin Cash",
  NEAR: "NEAR Protocol",
  MATIC: "Polygon",
  POL: "Polygon",
  LTC: "Litecoin",
  ICP: "Internet Computer",
  UNI: "Uniswap",
  ETC: "Ethereum Classic",
  XLM: "Stellar",
  ATOM: "Cosmos",
  OKB: "OKB",
  INJ: "Injective",
  APT: "Aptos",
  FIL: "Filecoin",
  HBAR: "Hedera",
  ARB: "Arbitrum",
  OP: "Optimism",
  VET: "VeChain",
  MKR: "Maker",
  GRT: "The Graph",
  RUNE: "THORChain",
  AAVE: "Aave",
  ALGO: "Algorand",
  FTM: "Fantom",
  S: "Sonic",
  EGLD: "MultiversX",
  SAND: "The Sandbox",
  MANA: "Decentraland",
  THETA: "Theta Network",
  XTZ: "Tezos",
  AXS: "Axie Infinity",
  FLOW: "Flow",
  CHZ: "Chiliz",
  EOS: "EOS",
  CAKE: "PancakeSwap",
  NEO: "Neo",
  KAVA: "Kava",
  CRV: "Curve DAO",
  SNX: "Synthetix",
  ZEC: "Zcash",
  DASH: "Dash",
  ENJ: "Enjin Coin",
  BAT: "Basic Attention Token",
  COMP: "Compound",
  ZIL: "Zilliqa",
  ONE: "Harmony",
  QTUM: "Qtum",
  SUI: "Sui",
  SEI: "Sei",
  TIA: "Celestia",
  PEPE: "Pepe",
  WIF: "dogwifhat",
  BONK: "Bonk",
  FLOKI: "FLOKI",
  JUP: "Jupiter",
  PYTH: "Pyth Network",
  RENDER: "Render",
  FET: "Artificial Superintelligence Alliance",
  TAO: "Bittensor",
  WLD: "Worldcoin",
  IMX: "Immutable",
  STX: "Stacks",
  LDO: "Lido DAO",
  DYDX: "dYdX",
  GALA: "Gala",
  APE: "ApeCoin",
  ENS: "Ethereum Name Service",
  MINA: "Mina",
  ROSE: "Oasis Network",
  KSM: "Kusama",
  AR: "Arweave",
  CFX: "Conflux",
  ASTR: "Astar",
  CELO: "Celo",
  HOT: "Holo",
  IOTA: "IOTA",
  KLAY: "Klaytn",
  WAVES: "Waves",
  XMR: "Monero",
  DAI: "Dai",
  BUSD: "Binance USD",
  WBTC: "Wrapped Bitcoin",
  ONDO: "Ondo",
  ENA: "Ethena",
  STRK: "Starknet",
  ZK: "ZKsync",
  W: "Wormhole",
  NOT: "Notcoin",
  ORDI: "ORDI",
  BLUR: "Blur",
  JASMY: "JasmyCoin",
  RSR: "Reserve Rights",
  ANKR: "Ankr",
  SKL: "SKALE",
  IOTX: "IoTeX",
  TWT: "Trust Wallet Token",
  GMT: "STEPN",
  OCEAN: "Ocean Protocol",
  MASK: "Mask Network",
  LRC: "Loopring",
  YFI: "yearn.finance",
  SUSHI: "SushiSwap",
  ZRX: "0x Protocol",
  BAL: "Balancer",
  UMA: "UMA",
  BAND: "Band Protocol",
  KNC: "Kyber Network Crystal",
  STORJ: "Storj",
  ICX: "ICON",
  ONT: "Ontology",
  RVN: "Ravencoin",
  SC: "Siacoin",
  DGB: "DigiByte",
  XVG: "Verge",
  NANO: "Nano",
  OMG: "OMG Network",
};

export function getCoinName(symbol: string): string {
  const upper = symbol.toUpperCase();
  return COIN_NAMES[upper] || upper;
}
